# Use the official MySQL Docker image
FROM mysql:8.0

# Set the root user password for the first instance
ENV MYSQL_ROOT_PASSWORD default1111

# Create the first MySQL container on port 3306
ENV MYSQL_DATABASE rentify
ENV MYSQL_USER user1
ENV MYSQL_PASSWORD password1
ENV MYSQL_PORT 3306
EXPOSE $MYSQL_PORT

# Set up the entrypoint script to create databases and users
COPY entrypoint_mysql.sh /docker-entrypoint-initdb.d/entrypoint_mysql.sh
RUN chmod +x /docker-entrypoint-initdb.d/entrypoint_mysql.sh

# Grant all privileges on the databases
RUN echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;" > /docker-entrypoint-initdb.d/grant-permissions.sql

# Set the default character set and collation
RUN echo "[mysqld]" >> /etc/mysql/my.cnf
RUN echo "character-set-server=utf8mb4" >> /etc/mysql/my.cnf
RUN echo "collation-server=utf8mb4_unicode_ci" >> /etc/mysql/my.cnf